export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const SET_PRODUCTS_LIST = 'SET_PRODUCTS_LIST';

export const FETCH_BRANDS = 'FETCH_BRANDS';
export const SET_BRANDS = 'SET_BRANDS';

export const SORT_PRICE = 'SORT_PRICE';
export const SET_SORT_PRICE = 'SET_SORT_PRICE';

export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';

export const SUBMIT_DATA = 'SUBMIT_DATA';
export const SET_SUBMIT_DATA = 'SET_SUBMIT_DATA';

export const PRODUCTS_SPEC = 'PRODUCTS_SPEC';
export const SET_PRODUCTS_SPEC = 'SET_PRODUCTS_SPEC';
// export const REMOVE_FILTER ='REMOVE_FILTER';
// export const SET_REMOVE_FILTER ='REMOVE_FILTER';
